# permissions to do viewer nodesimulators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodesimulator-viewer-role
rules:
- apiGroups:
  - sim.k8s.io
  resources:
  - nodesimulators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sim.k8s.io
  resources:
  - nodesimulators/status
  verbs:
  - get
